apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  ports:
    - name: http
      port: 3001
      targetPort: 3000
  selector:
    name: api

---

apiVersion: v1
kind: Service
metadata:
  name: slackbot
  labels:
    app: slackbot
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    name: slackbot

