apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      name: api
  template:
    metadata:
      labels:
        name: api
    spec:
      containers:
        - name: application
          image: '{{ .Values.ecrUrl }}:{{ .Values.imageTag }}'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          readinessProbe:
              httpGet:
                path: /healthz
                port: 3000
              initialDelaySeconds: 2
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-token
                  key: github-token
            - name: GIN_MODE
              value: "release"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: slackbot
spec:
  replicas: 1
  selector:
    matchLabels:
      name: slackbot
  template:
    metadata:
      labels:
        name: slackbot
    spec:
      containers:
        - name: application
          image: '{{ .Values.ecrUrl }}:{{ .Values.slackbotImageTag }}'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: ENVIRONMENT
              value: "production"
            - name: SLACK_APP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-app-token
                  key: slack-app-token
            - name: SLACK_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  name: slack-signing-secret
                  key: slack-signing-secret
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-bot-token
                  key: slack-bot-token

