name: Build and Push

on:
  workflow_call:
    inputs:
      env:
        description: 'which environment to deploy to'
        required: true
        type: string
      image_tag:
        description: 'what to tag the image with'
        type: string
      ecr_repo:
        description: 'name of the ecr repo'
        required: true
        type: string
      aws_region:
        description: 'region of the ecr repo'
        type: string
        required: true
    secrets:
      ecr_role_to_assume:
        description: 'ecr role to assume in aws'
        required: true
    # Map the workflow outputs to job outputs
    outputs:
      REGISTRY:
        description: "The ecr registry"
        value: ${{ jobs.build-and-push.outputs.registry }}

jobs:
  build-and-push:
    name: Build container, push to ECR and deploy to the cluster
    environment: ${{ inputs.env }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    outputs:
      IMAGE_TAG: ${{ steps.build-image.outputs.IMAGE_TAG }}
      REGISTRY: ${{ steps.login-ecr.outputs.registry }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ecr_role_to_assume }}
          aws-region: ${{ inputs.aws_region }}

      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REPO: ${{ inputs.ecr_repo }}
          IMAGE_TAG: ${{ inputs.image_tag }}
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $REGISTRY/$ECR_REPO:$IMAGE_TAG .
          docker push $REGISTRY/$ECR_REPO:$IMAGE_TAG
