name: Test Dockerfile
on: pull_request

jobs:
  dockerfile-test:
    name: container-structure-test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Build
        run: docker build -t api-test .
      - name: Check it exists
        run: docker images

      - name: Run docker tests
        uses: docker://gcr.io/gcp-runtimes/container-structure-test:latest
        with:
          args: "test --image api-test --config docker-test.yaml"
